### ISSUE TITLE
Changing a tag is unacceptable

### ISSUE THREAD

**Issue by dotlambda** [maxbachmann/jarowinkler-cpp#4]
The tag `v1.0.1` was changed from 99c236d34e9f4cff9f700c9913487c3c7515f220 to cea663e7db48bee9e6fc6d6d17f4927d46db1840.
However distributions use a hash to check a tarball's integrity and such a change leads to broken packages.

**Comment by maxbachmann** [comment]
Yeah your right. I reverted the tag to https://github.com/maxbachmann/jarowinkler-cpp/commit/99c236d34e9f4cff9f700c9913487c3c7515f220 and released the version number fix as `v1.0.2`

**Comment by dotlambda** [comment]
Thanks!
